name: Cypress tests

on: push
# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  Test:
    env:
      ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPORT: 5432
      DATABASE_URL: postgresql://postgres@127.0.0.1/basetool

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install zx & dotenv
      run: yarn global add zx
    - name: Copy env variables
      run: cp .env.test.sample .env.test
    - name: Migrate
      run: npx zx ./scripts/test:migrate.mjs
    - name: Install deps
      run: yarn install
    - uses: cypress-io/github-action@v2
      env:
        NODE_ENV: test
        PORT: 4099
      with:
        start: next dev -p 4099
