name: Cypress tests

on: push
# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master

jobs:
  Test:
    env:
      ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPORT: 5432
      DATABASE_URL: postgresql://postgres@127.0.0.1/basetool

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install zx & dotenv
      run: npm i -g add zx dotenv
    - name: Copy env variables
      run: cp .env.test.sample .env.test
    - name: Get yarn cache directory path
      id: production-yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: production-yarn-cache
      with:
        path: ${{ steps.production-yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-production-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-production-yarn-
    - name: Install deps
      run: yarn install
    - name: Migrate
      run: yarn dotenv -e .env.test -- yarn prisma migrate dev
    - uses: cypress-io/github-action@v2
      env:
        NODE_ENV: test
        PORT: 4099
      with:
        start: next dev -p 4099
